audience_hero_img_show:
    path: /
    methods: ["GET", "HEAD"]
    defaults:
        _controller: "AudienceHeroImageServerBundle:Img:show"

audience_hero_img_show_alt:
    path: "/{size}/{crop}/{url}"
    methods: ["GET", "HEAD"]
    defaults:
        crop: "none"
        _controller: "AudienceHeroImageServerBundle:Img:show"

