language: php
php: [7.1, nightly]

before_install:
    - printf "\n" | pecl install imagick

before_script:
    - composer selfupdate
    - composer require satooshi/php-coveralls ~1.0.0
    - composer install

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v
